# This is a basic workflow to help you get started with Actions
# all scripts are baased on the testing scripts for MagPiDownloader by @rubemlrm

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: pCYSl5EDgo/cat@master
        id: read_recent
        with:
          path: regular-issues.txt
      - run: |
          echo "ISSUE_NUMBER=${{ steps.read_recent.outputs.text }}" >> $GITHUB_ENV
          echo "ISSUE_MINUS_ONE=$((${{ steps.read_recent.outputs.text }}-1))" >> $GITHUB_ENV
          echo "ISSUE_MINUS_FIVE=$((${{ steps.read_recent.outputs.text }}-5))" >> $GITHUB_ENV
          echo "ISSUE_MINUS_SIX=$((${{ steps.read_recent.outputs.text }}-6))" >> $GITHUB_ENV

      - name: Download Issues With start limit
        id: normalIssuesWithStartLimit
        shell: pwsh
        run: ./helloworld-downloader.ps1 -f ${{ env.ISSUE_MINUS_ONE }}
      - name: Download Issues With end limit
        id: normalIssuesWithEndLimit
        shell: pwsh
        run: ./helloworld-downloader.ps1 -l 2
      - name: Download Issues with start and end limit
        id: normalIssuesWithRange
        shell: pwsh
        run: ./helloworld-downloader.ps1 -f ${{ env.ISSUE_MINUS_SIX }} -l ${{ env.ISSUE_MINUS_FIVE }}
        # https://github.com/marketplace/actions/file-existence
      - name: "Check file existence Windows"
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: "issues/hello-world-issue-3.pdf, issues/hello-world-issue-6.pdf, issues/hello-world-issue-14.pdf"
          allow_failure: false
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1
  bash-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: pCYSl5EDgo/cat@master
        id: read_recent
        with:
          path: regular-issues.txt
      - run: |
          echo "ISSUE_NUMBER=${{ steps.read_recent.outputs.text }}" >> $GITHUB_ENV
          echo "ISSUE_MINUS_ONE=$((${{ steps.read_recent.outputs.text }}-1))" >> $GITHUB_ENV
          echo "ISSUE_MINUS_FIVE=$((${{ steps.read_recent.outputs.text }}-5))" >> $GITHUB_ENV
          echo "ISSUE_MINUS_SIX=$((${{ steps.read_recent.outputs.text }}-6))" >> $GITHUB_ENV

      - name: Download Issues with end limit
        id: normalIssuesWithLimit
        run: bash ./helloworld-downloader.sh -l 2
      - name: Download Issues with start limit
        id: normalIssuesWithLimit
        run: bash ./helloworld-downloader.sh -f ${{ env.ISSUE_MINUS_ONE }}

      - name: Download Issues with start and end limit
        id: normalIssuesWithRange
        run: bash ./helloworld-downloader.sh -f ${{ env.ISSUE_MINUS_SIX }} -l ${{ env.ISSUE_MINUS_FIVE }}
      - name: "Check file existence Linux"
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: "issues/HelloWorld01.pdf, issues/HelloWorld_14_digital.pdf"
          allow_failure: false
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1        
  bash-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: pCYSl5EDgo/cat@master
        id: read_recent
        with:
          path: regular-issues.txt
      - run: |
          echo "ISSUE_NUMBER=${{ steps.read_recent.outputs.text }}" >> $GITHUB_ENV
          echo "ISSUE_MINUS_ONE=$((${{ steps.read_recent.outputs.text }}-1))" >> $GITHUB_ENV
          echo "ISSUE_MINUS_FIVE=$((${{ steps.read_recent.outputs.text }}-5))" >> $GITHUB_ENV
          echo "ISSUE_MINUS_SIX=$((${{ steps.read_recent.outputs.text }}-6))" >> $GITHUB_ENV

      - name: Download Issues with start limit
        id: normalIssuesWithStartLimit
        run: bash ./helloworld-downloader.sh -f ${{ env.ISSUE_MINUS_ONE }}
      - name: Download Issues with end limit
        id: normalIssuesWithEndLimit
        run: bash ./helloworld-downloader.sh -l 3        
      - name: Download Issues with start and end limit
        id: normalIssuesWithRange
        run: bash ./helloworld-downloader.sh -f ${{ env.ISSUE_MINUS_SIX }} -l ${{ env.ISSUE_MINUS_FIVE }}
      - name: lsah
        id: lslah
        run: ls -lah issues/
      # https://github.com/marketplace/actions/file-existence
      - name: "Check file existence Mac"
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: "issues/HelloWorld01.pdf, issues/HelloWorld06.pdf, issues/HelloWorld_14_digital.pdf"
          allow_failure: false
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1
